In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [10]:
dataset=pd.read_csv('titanic.csv')
dataset

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [11]:
dataset.isnull().any()

PassengerId    False
Survived       False
Pclass         False
Name           False
Sex            False
Age             True
SibSp          False
Parch          False
Ticket         False
Fare           False
Cabin           True
Embarked        True
dtype: bool

In [12]:
dataset.drop(['PassengerId','Name','Ticket','Fare','SibSp','Parch','Cabin'],axis=1,inplace=True)

In [13]:
dataset

Survived  Pclass     Sex   Age Embarked
0           0       3    male  22.0        S
1           1       1  female  38.0        C
2           1       3  female  26.0        S
3           1       1  female  35.0        S
4           0       3    male  35.0        S
..        ...     ...     ...   ...      ...
886         0       2    male  27.0        S
887         1       1  female  19.0        S
888         0       3  female   NaN        S
889         1       1    male  26.0        C
890         0       3    male  32.0        Q

[891 rows x 5 columns]

In [14]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    object 
 3   Age       714 non-null    float64
 4   Embarked  889 non-null    object 
dtypes: float64(1), int64(2), object(2)
memory usage: 34.9+ KB


In [15]:
dataset.shape

(891, 5)

In [19]:
dataset.head()

Survived  Pclass     Sex   Age Embarked
0         0       3    male  22.0        S
1         1       1  female  38.0        C
2         1       3  female  26.0        S
3         1       1  female  35.0        S
4         0       3    male  35.0        S

In [20]:
dataset.isnull().any()

Survived    False
Pclass      False
Sex         False
Age          True
Embarked     True
dtype: bool

In [22]:
dataset['Age'].fillna((dataset['Age'].mean()),inplace=True)

In [24]:
dataset['Embarked'].fillna(dataset['Embarked'].mode().iloc[0],inplace=True)#categorical column fill with mode

In [25]:
dataset.isnull().any()

Survived    False
Pclass      False
Sex         False
Age         False
Embarked    False
dtype: bool

In [27]:
x=dataset.iloc[:,1:].values #seperating dependent and independent variables  #conversion of numpy arrays
y=dataset.iloc[:,0].values
x

array([[3, 'male', 22.0, 'S'],
       [1, 'female', 38.0, 'C'],
       [3, 'female', 26.0, 'S'],
       ...,
       [3, 'female', 29.69911764705882, 'S'],
       [1, 'male', 26.0, 'C'],
       [3, 'male', 32.0, 'Q']], dtype=object)

In [28]:
y

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,

In [29]:
from sklearn.preprocessing import LabelEncoder #male female column filled with 1's and 0's
le=LabelEncoder()
x[:,1]=le.fit_transform(x[:,1])

In [30]:
x

array([[3, 1, 22.0, 'S'],
       [1, 0, 38.0, 'C'],
       [3, 0, 26.0, 'S'],
       ...,
       [3, 0, 29.69911764705882, 'S'],
       [1, 1, 26.0, 'C'],
       [3, 1, 32.0, 'Q']], dtype=object)

In [31]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [39]:
ct=ColumnTransformer([("one",OneHotEncoder(drop='first'),[1,3])],remainder="passthrough")#drop of 1st is used to dropn the dummy variable
x=ct.fit_transform(x)
x

array([[1.0, 1.0, 0.0, 3, 22.0],
       [0.0, 0.0, 0.0, 1, 38.0],
       [1.0, 0.0, 0.0, 3, 26.0],
       ...,
       [1.0, 0.0, 0.0, 3, 29.69911764705882],
       [0.0, 1.0, 0.0, 1, 26.0],
       [0.0, 1.0, 1.0, 3, 32.0]], dtype=object)

In [33]:
x.ndim

2

In [41]:
x

array([[1.0, 1.0, 0.0, 3, 22.0],
       [0.0, 0.0, 0.0, 1, 38.0],
       [1.0, 0.0, 0.0, 3, 26.0],
       ...,
       [1.0, 0.0, 0.0, 3, 29.69911764705882],
       [0.0, 1.0, 0.0, 1, 26.0],
       [0.0, 1.0, 1.0, 3, 32.0]], dtype=object)

In [40]:
y

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,

In [36]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [37]:
x_train.shape

(712, 5)

In [38]:
x_test.shape

(179, 5)